/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wintermute.curso.demo;

import org.junit.Test;

import com.wintermute.curso.demo.demos.Demo1;

import static org.junit.Assert.*;

public class Demo1Test {
    @Test public void testAppHasAGreeting() {
        Demo1 classUnderTest = new Demo1();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
