/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wintermute.curso.demo.demos;

import java.lang.Thread.UncaughtExceptionHandler;

public class Demo1 {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new Demo1().getGreeting());
        Thread thread = new Thread(new Runnable() {
			
			@Override
			public void run() {
				 System.out.println("We are in thread: "+Thread.currentThread().getName());
				 System.out.println("Thread priority: "+Thread.currentThread().getPriority());
				 throw new RuntimeException("Intentional exception");
			}
		});
        thread.setName("Mi hilo");
        thread.setPriority(Thread.MAX_PRIORITY);
        thread.setUncaughtExceptionHandler(new UncaughtExceptionHandler() {
			
			@Override
			public void uncaughtException(Thread t, Throwable e) {
				System.out.println("Ocurrió un error crítico "+e.getMessage());
				e.printStackTrace();
			}
		});
        System.out.println("We are in thread: "+Thread.currentThread().getName()+" Before new thread");
        thread.start();
        System.out.println("We are in thread: "+Thread.currentThread().getName()+" After new thread");
        
        Thread.sleep(10000);
    }
}
